# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7afc0126fa1796d9c532136beae9458172f238d31d743afe9c04cb0796410127f9609119fa8b5d8aa595949234ee4e5d9bc23b2fa88ffcb6d6a541f38c6e12d7

test:
  secret_key_base: 326d959838273b86eb444b8486f9f1695c7e9af1215c613bda8e69aea23ff57f0c1419305a3f84553b04f766030b855e9f60e5d49c5a7bc5c22f03811ae2e61a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
